# Generated by Django 5.0 on 2024-09-07 14:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Books",
            new_name="Book",
        ),
        migrations.RenameModel(
            old_name="Items",
            new_name="Item",
        ),
        migrations.RenameModel(
            old_name="Users",
            new_name="User",
        ),
        migrations.RenameModel(
            old_name="UserBooks",
            new_name="UserBook",
        ),
    ]
